export const DATA = {
	code: 0,
	msg: "SUCCESS",
	data: [
		{
			id: "2",
			carbonCoin: 5,
			frequency: 1,
			cycle: "1",
			type: 3,
			imgUrl: "111",
			name: "每日步行",
			category: 2,
			categorySub: 1,
			carbonReductionValue: 0.031,
			callWord: "步行或骑行更加有益身体健康，同时平均减少二氧化碳排放0.031kg/分钟。",
			isCompleted: 0
		},
		{
			id: "3",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 4,
			imgUrl: "11",
			name: "一餐素食",
			category: 2,
			categorySub: 2,
			carbonReductionValue: 0.76,
			callWord: "用一餐素食取代肉类，可平均减少0.76kg的二氧化碳排放。",
			isCompleted: 0
		},
		{
			id: "4",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 5,
			imgUrl: null,
			name: "使用可重复利用的餐具、吸管、杯子",
			category: 2,
			categorySub: 2,
			carbonReductionValue: 0.03,
			callWord: "用自备餐具和杯子比用一次性替代品，每次可减少约0.03kg的二氧化碳排放",
			isCompleted: 0
		},
		{
			id: "5",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 6,
			imgUrl: null,
			name: "光盘行动",
			category: 2,
			categorySub: 2,
			carbonReductionValue: 0.039,
			callWord: "光盘行动，每餐平均可减少0.039kg的二氧化碳排放。",
			isCompleted: 0
		},
		{
			id: "6",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 7,
			imgUrl: null,
			name: "不过量食用肉制品",
			category: 2,
			categorySub: 2,
			carbonReductionValue: 0.375,
			callWord:
				"肉制品在养殖、运输过程中会造成更多的碳排放，过量食用肉制品也不利于身体健康，中国营养学会建议每人每天不食用超过0.075kg畜禽肉类",
			isCompleted: 0
		},
		{
			id: "7",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 8,
			imgUrl: null,
			name: "带饭或自己做饭",
			category: 2,
			categorySub: 2,
			carbonReductionValue: 0.1,
			callWord: "带饭或自己做饭，可以吃的更加健康营养，同时还可减少使用食品包装袋。",
			isCompleted: 0
		},
		{
			id: "8",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 9,
			imgUrl: null,
			name: "优化飞行计划",
			category: 2,
			categorySub: 1,
			carbonReductionValue: 3.84,
			callWord: "原本计划乘坐飞机出差，改为高铁等低碳排放出行，或取消非必要的差旅。",
			isCompleted: 0
		},
		{
			id: "9",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 10,
			imgUrl: null,
			name: "绿色骑行",
			category: 2,
			categorySub: 1,
			carbonReductionValue: 0.031,
			callWord: "步行或骑行更加有益身体健康，同时平均减少二氧化碳排放0.031kg/分钟。",
			isCompleted: 0
		},
		{
			id: "10",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 11,
			imgUrl: null,
			name: "乘坐公共交通",
			category: 2,
			categorySub: 1,
			carbonReductionValue: 98.0,
			callWord: "每月少开1天车，相当于减少二氧化碳排放量98kg。",
			isCompleted: 0
		},
		{
			id: "11",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 12,
			imgUrl: null,
			name: "乘坐新能源汽车",
			category: 2,
			categorySub: 1,
			carbonReductionValue: 32.0,
			callWord: "乘坐新能源汽车，每公里可减少二氧化碳排放约0.106/公里。",
			isCompleted: 0
		},
		{
			id: "12",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 18,
			imgUrl: null,
			name: "垃圾分类",
			category: 2,
			categorySub: 3,
			carbonReductionValue: 0.078,
			callWord: "每个居民每次进行垃圾分类可以平均减少碳排放0.078kg。",
			isCompleted: 0
		},
		{
			id: "13",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 19,
			imgUrl: null,
			name: "采购本地生产的时令食材",
			category: 2,
			categorySub: 3,
			carbonReductionValue: 0.0,
			callWord: "采购本次生产的时令食品。",
			isCompleted: 0
		},
		{
			id: "14",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 20,
			imgUrl: null,
			name: "自带环保袋",
			category: 2,
			categorySub: 3,
			carbonReductionValue: 0.1,
			callWord: "少用1个塑料袋，相当于减少0.1kg的二氧化碳排放。",
			isCompleted: 0
		},
		{
			id: "15",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 21,
			imgUrl: null,
			name: "回收利用闲置物品",
			category: 2,
			categorySub: 3,
			carbonReductionValue: 0.037,
			callWord:
				"物尽其用是最低碳的生活方式，买少一点，用好一点，用久一点，如捐赠旧衣，二次利用闲置品都是最简单又最有效的减排方式。",
			isCompleted: 0
		},
		{
			id: "16",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 22,
			imgUrl: null,
			name: "节约用水",
			category: 2,
			categorySub: 3,
			carbonReductionValue: 0.91,
			callWord: "在洗漱等用水间歇，关闭水龙头，可以节约用水60%。",
			isCompleted: 0
		},
		{
			id: "17",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 13,
			imgUrl: null,
			name: "双面使用纸张",
			category: 2,
			categorySub: 4,
			carbonReductionValue: 0.01,
			callWord: "少浪费1500张纸，可以保留一棵树",
			isCompleted: 0
		},
		{
			id: "18",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 15,
			imgUrl: null,
			name: "少发邮件",
			category: 2,
			categorySub: 4,
			carbonReductionValue: 0.003,
			callWord: "一年每天发送20封邮件，相当于一辆汽车行驶1000公里所排放的温室气体量。",
			isCompleted: 0
		},
		{
			id: "19",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 14,
			imgUrl: null,
			name: "缩短开会时间",
			category: 2,
			categorySub: 4,
			carbonReductionValue: 0.18,
			callWord: "开短会也是一种节约，节约大家的时间，减少照明、空调、电子设备的使用。",
			isCompleted: 0
		},
		{
			id: "20",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 16,
			imgUrl: null,
			name: "随手关灯、关电器",
			category: 2,
			categorySub: 4,
			carbonReductionValue: 0.785,
			callWord: "出门前记得随手关灯和空调，每年至少可节约用电5度，相应的减少碳排放4.8kg。",
			isCompleted: 0
		},
		{
			id: "21",
			carbonCoin: 3,
			frequency: 1,
			cycle: "1",
			type: 17,
			imgUrl: null,
			name: "爬楼梯而非使用电梯",
			category: 2,
			categorySub: 4,
			carbonReductionValue: 0.218,
			callWord: "走楼梯上下一层楼能减少0.218kg的二氧化碳排放。",
			isCompleted: 0
		},
		{
			id: "22",
			carbonCoin: 10,
			frequency: 1,
			cycle: "365",
			type: 23,
			imgUrl: null,
			name: "完成Learn气候变化培训",
			category: 2,
			categorySub: 5,
			carbonReductionValue: 0.0,
			callWord: "iLearn平台共有4节气候变化课程，全部完成且拍照完成照片上传。",
			isCompleted: 0
		},
		{
			id: "23",
			carbonCoin: 10,
			frequency: 1,
			cycle: "365",
			type: 24,
			imgUrl: null,
			name: "参与拾捡活动",
			category: 2,
			categorySub: 5,
			carbonReductionValue: 1.4,
			callWord: "参与捡拾行动，每捡拾1kg废物并回收，就可以减少1.4kg的二氧化碳排放。",
			isCompleted: 0
		},
		{
			id: "24",
			carbonCoin: 10,
			frequency: 1,
			cycle: "365",
			type: 25,
			imgUrl: null,
			name: "参与种树活动",
			category: 2,
			categorySub: 5,
			carbonReductionValue: 100.0,
			callWord: "乘飞机2千公里或自驾车消耗100公升汽油，排放约280kg二氧化碳，种植3棵树即可抵消。",
			isCompleted: 0
		},
		{
			id: "25",
			carbonCoin: 10,
			frequency: 1,
			cycle: "365",
			type: 26,
			imgUrl: null,
			name: "其他活动",
			category: 2,
			categorySub: 5,
			carbonReductionValue: 0.0,
			callWord: "其他可以减少二氧化碳排放量的活动。",
			isCompleted: 0
		}
	]
};
